import './globals.css'
import type { Metadata } from 'next'
import ThemeRegistry from '@/theme/ThemeRegistry'
import { Inter } from 'next/font/google'
import JniFooter from '../components/JniFooter'
import JniAppBar from '../components/JniAppBar'
import { MessageBoardProvider } from '@/components/messageboard/MessageBoardProvider'
import MessageBoard from '@/components/messageboard/MessageBoard'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<ThemeRegistry>
				<body className={inter.className}>
					<JniAppBar />
					<MessageBoardProvider>
						<MessageBoard />
						{children}
					</MessageBoardProvider>
					<JniFooter />
				</body>
			</ThemeRegistry>
		</html>
	)
}
